name: varnishotel

volumes:
  varlibvarnish:

services:
  otel:
    image: grafana/otel-lgtm:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ORG_NAME=Main Org.
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
    ports:
      - "3000:3000" # grafana
      - "4317:4317" # otlp http/json
      - "4318:4318" # otlp grpc
      - "4040:4040" # pyroscope

  webplayground:
    build:
      dockerfile: contrib/webplayground/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080
    volumes:
      - ./contrib/webplayground/usr/share/nginx/html:/usr/share/nginx/html
      - ./contrib/webplayground/etc/nginx/conf.d:/etc/nginx/conf.d

  varnishcache:
    image: varnish:7.7.1
    ports:
      - "18080:18080"
      - "18443:18443"
    environment:
      - VARNISH_HTTP_PORT=18080
      - VARNISH_PROXY_PORT=18443
      - VARNISH_BACKEND_HOST=webplayground
      - VARNISH_BACKEND_PORT=80
    volumes:
      - varlibvarnish:/var/lib/varnish
      - ./contrib/varnish/default.vcl:/etc/varnish/default.vcl

  varnishotel:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_TRACES_SAMPLER=always_on
      - RUST_LOG=info
    volumes:
      - varlibvarnish:/var/lib/varnish