site_name: varnishotel
repo_url: https://github.com/thomasklinger1234/varnishotel
edit_uri: edit/main/docs
extra_css: []
site_dir: site

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Introduction: index.md
  - Quick start: quickstart.md
  - Design:
      - design/varnishlogreceiver.md
      - design/semconv.md

plugins:
  - search
  - mike