---
name: General support
description: Permissions issues, repository issues, etc
body:
  - id: problem
    type: textarea
    attributes:
      label: Describe the issue
      placeholder: A clear and concise description of what you need assistance with.
    validations:
      required: true