---
name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'mkdocs.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5 # pin@v3
        with:
          fetch-depth: 0 # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-systems-like-github-actions
      - uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'
      - uses: astral-sh/setup-uv@v6
      - run: |
          make docs-deps
          make docs-build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: "site"
      - id: deployment
        uses: actions/deploy-pages@v4